version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=smartparkinglotuser
      - POSTGRES_PASSWORD=smartparkinglotpassword
      - POSTGRES_DB=smartparkinglotdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartparkinglotuser -d smartparkinglotdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=smartparkinglotdb
      - POSTGRES_USER=smartparkinglotuser
      - POSTGRES_PASSWORD=smartparkinglotpassword
    command: ["sh", "-c", "npm run seed && npm start"]
