version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: smartlotuser
      POSTGRES_PASSWORD: smartlotpassword
      POSTGRES_DB: smartlotdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: